 #include "ast.tab.hpp"
#include <iostream>
#include <cstring>
#include <typeinfo>
#include <sstream>
using namespace std;
int comment;

#line 10 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 137
#define YY_END_OF_BUFFER 138
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[447] =
    {   0,
        0,    0,  138,  136,  135,  134,  135,   87,  136,  107,
      104,  136,   74,   75,  102,  100,   71,  101,   73,  103,
      126,  126,   90,   72,   86,   83,   84,   89,   79,  124,
       76,   77,  106,   14,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,   81,  105,   82,   88,  135,  135,
      135,   95,    0,    0,    0,  132,    0,  118,   96,  115,
        0,    2,  113,   98,  111,   99,  112,   91,    0,  125,
        1,    3,  114,  125,  128,    0,    0,  126,    0,  126,
      126,  126,   80,  108,   94,   85,   92,   93,  109,  124,

      117,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,   17,  124,  124,  124,  124,  124,  124,  124,  124,
       26,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,   65,  124,  124,  124,  124,  124,  124,  124,
      116,   97,    0,  135,  131,  131,    0,  131,  131,    0,
      133,   78,  125,  125,    0,    3,  125,  125,  128,  127,
        0,  130,  119,  120,  110,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,   25,  124,  124,  124,   31,  124,

      124,  124,   35,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,   51,  124,   68,  124,  124,
      124,  124,  124,  131,    0,  131,  125,    0,  125,  125,
      127,    0,    0,  130,  121,  124,  124,  124,  124,    8,
        9,  124,   11,  124,  124,  124,  124,  124,   19,   20,
      124,  124,  124,  124,  124,   27,  124,  124,  124,  124,
       33,  124,  124,    0,  123,   58,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,   47,  124,  124,  122,   67,   52,  124,  124,

       69,  124,  132,  125,    0,    0,    0,    0,    0,    0,
      124,  124,  124,    7,   10,   12,   13,  124,  124,  124,
      124,  124,   22,   24,  124,  124,  124,  124,  124,  124,
        0,   59,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,   43,  124,  124,   44,  124,  124,   48,  124,
      124,   54,   70,    0,  129,  129,    0,  129,  124,    5,
      124,  124,  124,   18,  124,  124,  124,  124,   29,  124,
      124,   56,   34,    0,  124,  124,  124,  124,  124,   39,
       62,  124,   40,   64,   41,  124,   45,  124,   49,  124,
      124,  129,  129,  129,  124,    6,  124,   16,   55,   21,

       23,  124,  124,  124,    0,   36,   60,   37,  124,  124,
      124,  124,  124,  124,  124,  124,    4,   15,  124,  124,
      124,    0,  124,   61,   63,   42,  124,  124,  124,   53,
      124,  124,   32,    0,   38,  124,   50,  124,   28,   30,
       57,  124,   66,  124,   46,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   29,   31,   32,   31,
       29,   29,   29,   29,   29,   33,   29,   29,   29,   34,
       29,   29,   29,   29,   29,   29,   29,   35,   29,   29,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,   51,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    4,    1,    5,    5,    5,
        5,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    5,    5,    5,    6,    6,    6,    6,    5,
        6,    5,    5,    5,    5,    5,    5,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    8,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[456] =
    {   0,
        0,    0,  693,  694,   69,  694,   70,  667,   73,  666,
       68,    0,  694,  694,   61,   67,  694,   69,   69,   79,
       95,  102,  668,  694,   57,  664,   72,  694,  694,    0,
      694,  694,  663,  694,   57,   43,   90,   73,   97,  103,
      631,  110,  630,  629,  112,  627,  121,  637,  120,   75,
      622,   85,   56,  631,  694,   76,  694,  694,  168,  169,
      174,  694,  155,  184,  187,  694,  677,  694,  694,  694,
      670,  694,  694,  694,  694,  694,  694,  694,  662,  180,
      694,    0,  694,  184,  216,  222,   89,  694,  661,  232,
      239,  694,  694,  651,  694,  694,  694,  694,  111,    0,

      694,  615,  614,  617,  626,  610,  134,  628,  627,  613,
      620,  604,  605,  602,  149,  610,  607,  605,  601,  598,
        0,  601,  136,  602,  611,  594,  590,  598,  599,  605,
      606,  590,  129,  605,  203,  605,  590,  180,  588,  594,
      588,   53,    0,  212,  596,  582,  164,  590,  578,  592,
      694,  694,  203,  269,  285,  631,  277,  290,  630,  214,
      694,  694,  279,  283,  315,    0,  300,  319,  694,  289,
        0,  192,  694,  694,  610,  573,  587,  579,  589,  584,
      583,  584,  568,  566,  206,  583,  581,  577,  568,  565,
      574,  559,  576,  575,    0,  560,  253,  554,  568,  565,

      550,  561,    0,  595,  556,  553,  555,  552,  542,  183,
      551,  547,  540,  539,  547,  540,  537,  547,  550,  534,
      550,  533,  536,  536,  544,    0,  529,    0,  543,  545,
      533,  536,  531,  284,  577,  338,  334,  338,  342,  348,
      694,  343,  348,  694,  694,  523,  522,  534,  527,    0,
        0,  529,    0,  517,  515,  525,  512,  520,    0,    0,
      513,  516,  524,  516,  507,    0,  521,  507,  523,  505,
        0,  510,  499,  501,    0,  500,  517,  508,  515,  510,
      505,  504,  494,  502,  492,  504,  488,  498,  503,  487,
      501,  495,    0,  479,  482,    0,    0,    0,  480,  494,

        0,  494,  532,  694,    0,  383,  393,  352,    0,  402,
      495,  475,  493,    0,    0,    0,    0,  479,  480,  486,
      470,  485,  476,    0,  474,  466,  471,  478,  478,  477,
      476,    0,  473,  458,  444,  441,  433,  425,  421,  405,
      408,  417,    0,  417,  399,    0,  410,  399,  396,  404,
      403,    0,    0,  406,  403,  410,    0,  420,  408,    0,
      394,  385,  385,    0,  385,  384,  377,  396,    0,  396,
      397,    0,    0,  396,  391,  376,  386,  358,  364,    0,
        0,  361,    0,    0,    0,  345,    0,  335,    0,  167,
      332,    0,  694,    0,  323,    0,  335,    0,    0,    0,

        0,  323,  330,  328,  318,    0,    0,    0,  324,  304,
      290,  292,  293,  288,  273,  271,    0,    0,  255,  257,
      266,  259,  250,    0,    0,    0,  232,  215,  205,    0,
      202,  209,    0,  188,    0,  163,    0,  173,    0,    0,
      694,  131,    0,  106,    0,  694,  467,  475,  479,  487,
      495,  503,  508,  510,  512
    } ;

static const flex_int16_t yy_def[456] =
    {   0,
      446,    1,  446,  446,  446,  446,  446,  446,  447,  446,
      446,  448,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  449,
      446,  446,  446,  446,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  446,  446,  446,  446,  446,  450,
      446,  446,  447,  451,  447,  446,  447,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  452,  446,  446,  446,  446,  446,  446,  453,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  449,

      446,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      446,  446,  450,  450,  450,  450,  451,  451,  450,  451,
      446,  446,  446,  446,  446,  452,  446,  446,  446,  446,
      454,  453,  446,  446,  446,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,

      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  450,  450,  451,  446,  446,  446,  446,
      446,  454,  455,  446,  446,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  446,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,

      449,  449,  450,  446,  242,  242,  446,  455,  308,  308,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      446,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  446,  306,  446,  308,  310,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  446,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  242,  446,  308,  449,  449,  449,  449,  449,  449,

      449,  449,  449,  449,  446,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  446,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  446,  449,  449,  449,  449,  449,  449,
      446,  449,  449,  449,  449,    0,  446,  446,  446,  446,
      446,  446,  446,  446,  446
    } ;

static const flex_int16_t yy_nxt[765] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   30,
       30,   30,   30,   30,   30,   31,    4,   32,   33,   34,
        4,   35,   36,   37,   38,   39,   40,   41,   30,   42,
       30,   30,   43,   44,   45,   46,   47,   30,   48,   49,
       50,   51,   52,   53,   30,   54,   55,   56,   57,   58,
       59,   60,   59,   61,   64,   69,   65,   72,   66,   74,
       94,   95,   96,   76,   79,   73,   80,   80,   80,   80,
       81,   75,   70,   77,   78,   82,   98,   99,  104,  102,

      151,  105,  222,   83,  148,  149,  170,  170,  106,   67,
       84,  223,   85,   85,   85,   86,  103,   84,  111,   90,
       91,   91,   91,  142,   87,   88,  146,   88,  112,   89,
      143,  107,   92,  144,   92,  174,  175,   87,  108,   88,
      147,   88,  109,  152,  116,  110,   92,   88,   92,  113,
      445,  114,  117,  126,   92,  118,  121,  127,  119,   89,
       66,  115,  131,  122,  123,  136,  132,  128,  137,   59,
      154,   59,  155,  129,  156,   60,  444,   61,  209,  133,
      138,  139,  134,  140,  210,  141,  153,  158,   64,  159,
       65,   67,   66,  181,  182,  198,  199,  163,  163,  163,

      163,  167,  167,  167,  167,  190,  234,  243,  156,  191,
      164,  165,  414,  229,  168,  165,  230,  158,  443,  236,
      160,  217,  442,   67,  164,  165,  164,  415,  168,  165,
      168,   84,  441,   85,   85,   85,   86,   84,  218,   86,
       86,   86,   86,  280,  244,  281,  212,   84,  169,   90,
       90,   90,   90,  224,   84,  440,   90,   91,   91,   91,
      213,  439,   92,  214,   92,  255,  256,  438,  169,   92,
      154,   92,  155,  225,  156,  437,   92,  226,   92,  153,
      158,  436,  159,   92,   92,   92,  154,  234,  155,  156,
      156,   92,  153,  158,  435,  159,  163,  163,  163,  163,

      237,  237,  237,  237,  434,  267,  170,  170,  268,  164,
      165,  433,  432,  160,  165,  431,  430,  167,  167,  167,
      167,  241,  429,  164,  165,  164,  160,  238,  165,  238,
      240,  165,  239,  239,  239,  239,  237,  237,  237,  237,
      153,  241,  428,  303,  240,  165,  240,  427,  426,  425,
      165,  237,  237,  237,  237,  239,  239,  239,  239,  239,
      239,  239,  239,  424,  165,  237,  237,  237,  237,  423,
      422,  421,  304,  305,  160,  420,  306,  419,  309,  165,
      418,  310,  357,  417,  416,  310,  304,  305,  304,  305,
      413,  412,  309,  165,  309,  354,  357,  354,  357,  307,

      355,  355,  355,  355,  307,  354,  411,  354,  307,  410,
      356,  356,  356,  356,  354,  446,  354,  446,  409,  358,
      358,  358,  358,  356,  356,  356,  356,  356,  356,  356,
      356,  408,  446,  392,  446,  407,  406,  405,  404,  403,
      393,  402,  401,  400,  399,  398,  397,  392,  396,  392,
      394,  395,  391,  390,  393,  389,  393,  388,  387,  386,
      385,  384,  383,  382,  394,  381,  394,   63,  380,   63,
       63,   63,   63,   63,   63,   71,   71,  379,   71,   71,
       71,   71,   71,  100,  378,  100,  100,  153,  153,  153,
      153,  153,  153,  153,  153,  157,  157,  157,  157,  157,

      157,  157,  157,  166,  377,  166,  166,  166,  166,  166,
      166,  172,  172,  172,  242,  242,  308,  308,  376,  308,
      375,  374,  373,  372,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  446,  353,  352,
      351,  350,  349,  348,  347,  346,  345,  344,  343,  342,
      341,  340,  339,  338,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  296,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  446,  302,  301,  300,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,

      285,  284,  283,  282,  279,  278,  277,  276,  275,  274,
      273,  272,  271,  270,  269,  266,  265,  264,  263,  262,
      261,  260,  259,  258,  257,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  235,  235,  233,  232,  231,
      228,  227,  221,  220,  219,  216,  215,  211,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  197,  196,  195,
      194,  193,  192,  189,  188,  187,  186,  185,  184,  183,
      180,  179,  178,  177,  176,  173,  171,  162,  161,   63,
      150,  145,  135,  130,  125,  124,  120,  101,   97,   93,
       68,   62,  446,    3,  446,  446,  446,  446,  446,  446,

      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446
    } ;

static const flex_int16_t yy_chk[765] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    7,    5,    7,    9,   11,    9,   15,    9,   16,
       25,   25,   25,   18,   19,   15,   19,   19,   19,   19,
       20,   16,   11,   18,   18,   20,   27,   27,   36,   35,

       56,   36,  142,   20,   53,   53,   87,   87,   36,    9,
       21,  142,   21,   21,   21,   21,   35,   22,   38,   22,
       22,   22,   22,   50,   21,   21,   52,   21,   38,   21,
       50,   37,   22,   50,   22,   99,   99,   21,   37,   21,
       52,   21,   37,   56,   40,   37,   22,   21,   22,   39,
      444,   39,   40,   45,   22,   40,   42,   45,   40,   21,
       63,   39,   47,   42,   42,   49,   47,   45,   49,   59,
       60,   59,   60,   45,   60,   61,  442,   61,  133,   47,
       49,   49,   47,   49,  133,   49,   64,   64,   65,   64,
       65,   63,   65,  107,  107,  123,  123,   80,   80,   80,

       80,   84,   84,   84,   84,  115,  153,  172,  153,  115,
       80,   80,  390,  147,   84,   84,  147,  160,  438,  160,
       64,  138,  436,   65,   80,   80,   80,  390,   84,   84,
       84,   85,  434,   85,   85,   85,   85,   86,  138,   86,
       86,   86,   86,  210,  172,  210,  135,   90,   85,   90,
       90,   90,   90,  144,   91,  432,   91,   91,   91,   91,
      135,  431,   90,  135,   90,  185,  185,  429,   85,   91,
      154,   91,  154,  144,  154,  428,   90,  144,   90,  157,
      157,  427,  157,   91,   90,   91,  155,  234,  155,  234,
      155,   91,  158,  158,  423,  158,  163,  163,  163,  163,

      164,  164,  164,  164,  422,  197,  170,  170,  197,  163,
      163,  421,  420,  157,  164,  419,  416,  167,  167,  167,
      167,  170,  415,  163,  163,  163,  158,  165,  164,  165,
      167,  167,  165,  165,  165,  165,  168,  168,  168,  168,
      236,  170,  414,  236,  167,  167,  167,  413,  412,  411,
      168,  237,  237,  237,  237,  238,  238,  238,  238,  239,
      239,  239,  239,  410,  168,  240,  240,  240,  240,  409,
      405,  404,  239,  242,  236,  403,  242,  402,  243,  240,
      397,  243,  308,  395,  391,  308,  239,  242,  239,  242,
      388,  386,  243,  240,  243,  306,  308,  306,  308,  242,

      306,  306,  306,  306,  243,  307,  382,  307,  308,  379,
      307,  307,  307,  307,  310,  355,  310,  355,  378,  310,
      310,  310,  310,  354,  354,  354,  354,  356,  356,  356,
      356,  377,  358,  355,  358,  376,  375,  374,  371,  370,
      356,  368,  367,  366,  365,  363,  362,  355,  361,  355,
      358,  359,  351,  350,  356,  349,  356,  348,  347,  345,
      344,  342,  341,  340,  358,  339,  358,  447,  338,  447,
      447,  447,  447,  447,  447,  448,  448,  337,  448,  448,
      448,  448,  448,  449,  336,  449,  449,  450,  450,  450,
      450,  450,  450,  450,  450,  451,  451,  451,  451,  451,

      451,  451,  451,  452,  335,  452,  452,  452,  452,  452,
      452,  453,  453,  453,  454,  454,  455,  455,  334,  455,
      333,  331,  330,  329,  328,  327,  326,  325,  323,  322,
      321,  320,  319,  318,  313,  312,  311,  303,  302,  300,
      299,  295,  294,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      274,  273,  272,  270,  269,  268,  267,  265,  264,  263,
      262,  261,  258,  257,  256,  255,  254,  252,  249,  248,
      247,  246,  235,  233,  232,  231,  230,  229,  227,  225,
      224,  223,  222,  221,  220,  219,  218,  217,  216,  215,

      214,  213,  212,  211,  209,  208,  207,  206,  205,  204,
      202,  201,  200,  199,  198,  196,  194,  193,  192,  191,
      190,  189,  188,  187,  186,  184,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  159,  156,  150,  149,  148,
      146,  145,  141,  140,  139,  137,  136,  134,  132,  131,
      130,  129,  128,  127,  126,  125,  124,  122,  120,  119,
      118,  117,  116,  114,  113,  112,  111,  110,  109,  108,
      106,  105,  104,  103,  102,   94,   89,   79,   71,   67,
       54,   51,   48,   46,   44,   43,   41,   33,   26,   23,
       10,    8,    3,  446,  446,  446,  446,  446,  446,  446,

      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[138] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "df.l"

#line 800 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 19 "df.l"


#line 1020 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 447 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 694 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 21 "df.l"
{comment=1;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 22 "df.l"
{if(comment)comment=0; else{cout << "Error: unexpected */ in line-" << yylineno;}}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 23 "df.l"

	YY_BREAK
case 4:
YY_RULE_SETUP
#line 25 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(abstract);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 26 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(assert);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 27 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(boolean);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 28 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(break1);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 29 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(byte1);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 30 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(case1);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 31 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(catch1);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 32 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(char1);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 33 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(class1);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 34 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(const1);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 35 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(underscore);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 36 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(continue1);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 37 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(default1);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 38 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(do1);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 39 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(double1);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 40 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(else1);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 41 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(enum1);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 42 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(extends);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 43 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(final);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 44 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(finally);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 45 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(float1);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 46 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(for1);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 47 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(if1);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 48 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(goto1);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 49 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(implements);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 50 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(import);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 51 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(instanceof);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 52 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(int1);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 53 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(interface);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 54 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(long1);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 55 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(native);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 56 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(new1);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 57 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(package);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 58 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(private1);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 59 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(protected1);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 60 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(public1);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 61 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(return1);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 62 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(static1);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 63 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(strictfp);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 64 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(short1);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 65 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(super);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 66 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(switch1);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 67 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(synchronised);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 68 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(this1);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 69 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(throw1);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 70 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(throws);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 71 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(transient);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 72 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(try1);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 73 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(void1);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 74 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(volatile1);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 75 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(while1);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 77 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(exports);} 
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 78 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(module1);} 
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 79 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(NonSealed);} 
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 80 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(open);} 
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 81 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(opens);} 
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 82 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(permits);} 
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 83 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(provides);} 
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 84 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(record);} 
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 85 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(requires1);} 
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 86 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(sealed);} 
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 87 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(to);} 
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 88 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(transitive);} 
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 89 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(uses);} 
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 90 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(var);} 
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 91 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(with);} 
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 92 "df.l"
{if(!comment)yylval.str=strdup(yytext); return(yield);} 
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 94 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(comma);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 95 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(semicolon);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 96 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(period);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 97 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(open_bracket);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 98 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(closed_bracket);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 99 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(open_square_bracket);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 100 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(closed_square_bracket);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 101 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(dots_three);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 102 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(at);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 103 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(colon_colon);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 104 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(open_flower_bracket);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 105 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(closed_flower_bracket);} 
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 107 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(equal1);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 108 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(gthan);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 109 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(diamond);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 110 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(lthan);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 111 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(exclamatory);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 112 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(notk);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 113 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(qmark);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 114 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(colon);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 115 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(implies);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 116 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(equal_equal);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 117 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(g_equal);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 118 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(l_equal);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 119 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(exclamatory_equal);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 120 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(and_and);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 121 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(or1);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 122 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(increment);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 123 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(decrement);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 124 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(plus_1);}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 125 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(minus_1);}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 126 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(multiply);}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 127 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(divide);}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 128 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(band);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 129 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(bor);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 130 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(power);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 131 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(percentage);}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 132 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(llthan);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 133 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(ggthan);}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 134 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(gggthan);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 135 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(plus_equal);}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 136 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(minus_equal);}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 137 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(multiply_equal);}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 138 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(divide_equal);}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 139 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(bitand_equal);}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 140 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(bitor_equal);}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 141 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(power_equal);}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 142 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(percentage_equal);}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 143 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(ll_equal);}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 144 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(gg_equal);}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 145 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(ggg_equal);}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 147 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(BooleanLiteral);}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 149 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(NullLiteral);}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 151 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(identifier);}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 153 "df.l"
{if(!comment)yylval.fval=atof(strdup(yytext));return(decfloat);}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 155 "df.l"
{if(!comment)yylval.ival=atoi(strdup(yytext));return(decint);}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 157 "df.l"
{if(!comment)yylval.ival=atoi(strdup(yytext));return(binint);}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 159 "df.l"
{if(!comment)yylval.ival=atoi(strdup(yytext));return(octint);}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 161 "df.l"
{if(!comment)yylval.fval=atof(strdup(yytext));return(hexfloat1);}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 163 "df.l"
{if(!comment)yylval.ival=atoi(strdup(yytext));return(hexint);}
	YY_BREAK
case 131:
/* rule 131 can match eol */
YY_RULE_SETUP
#line 165 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(textblock);}
	YY_BREAK
case 132:
/* rule 132 can match eol */
YY_RULE_SETUP
#line 167 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(string1);}
	YY_BREAK
case 133:
/* rule 133 can match eol */
YY_RULE_SETUP
#line 169 "df.l"
{if(!comment)yylval.str=strdup(yytext);return(charlit);}
	YY_BREAK
case 134:
/* rule 134 can match eol */
YY_RULE_SETUP
#line 171 "df.l"

	YY_BREAK
case 135:
YY_RULE_SETUP
#line 173 "df.l"

	YY_BREAK
case 136:
YY_RULE_SETUP
#line 175 "df.l"
{if(!comment)cout << "Error in line:" << yylineno << ",uncognized token:" << yytext << "\n";}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 176 "df.l"
ECHO;
	YY_BREAK
#line 1776 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 447 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 447 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 446);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 176 "df.l"

